### ISSUE TITLE
`Message: Transaction simulation failed: Attempt to load a program that does not exist.` after fresh clone

### ISSUE THREAD

**Issue by Chralt98** [CKS-Systems/manifest#146]
I try to run the script `sh local-validator-test.sh`, but get errors after a fresh clone.

I assume that `cargo build-sbf` has generated the wrong keypair files for the programs.

Those generated keypair files have different public addresses to the expected ones in the programs:

I expected to receive the keypair files for `MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms`, `wMNFSTkir3HgyZTsB7uqu3i7FA73grFCptPXgrZjksL`, `UMnFStVeG1ecZFc2gc5K3vFy3sMpotq8C91mXBQDGwh`.

What is the best practice to successfully run the typescript tests locally?

**Comment by brittcyr** [comment]
How recent is your checkout?

Should have been addressed here
https://github.com/CKS-Systems/manifest/pull/97/files#diff-874260e9743eebbba4a833541500ec32a264f674f7c4bd18f13d19efa369c674

**Comment by Chralt98** [comment]
Yeah, my last commit was this one 7d675c30dce2376466c27c359c81db5389168b9e. Thanks!
