### ISSUE TITLE
What is a `PostOnly` order?

### ISSUE THREAD

**Issue by Chralt98** [CKS-Systems/manifest#231]
https://github.com/CKS-Systems/manifest/blob/0151867364bb294cb3267ed90e938fae17c2a497/programs/manifest/src/state/resting_order.rs#L28-L35

I am trying to understand when I should use `PostOnly` and when `Limit`.

I understand the principle of a limit order, but what is `PostOnly` then?

**Comment by brittcyr** [comment]
PostOnly is an order that behaves like a limit order but fails if it would cross and match. This is common in other exchanges where taker fees are high, so when placing an order if a price would not be profitable for you after factoring in fees, it gets cancelled. For our use case without fees, it is useful if your strategy wants to be adding liquidity to the book only. There can be a number of reasons for that. Note that if you make a wrapper that moves your orders to not cross, then this functionality can be entirely done in a wrapper.
